### ISSUE TITLE
fix dropfile and flashcanvas support

### ISSUE THREAD

**Issue by draeton** [draeton/stitches#1]
This tool should be supported in the major browsers, including IE and Safari. Dropfile and Flashcanvas are included, but they need to be linked up to the existing code.

**Comment by draeton** [comment]
Might adjust the milestone on this one, just because there have been so many additional changes that I feel deserve 0.1 status

**Comment by InsidiousForce** [comment]
works in ie10 fyi, just tested the demo and it works fine.

**Comment by draeton** [comment]
Thanks for letting me know. I take as a personal challenge to support older versions of IE, but in this case, I haven't really been all that interested in following through. Glad to see that 10 is up to snuff.

**Comment by draeton** [comment]
Closing this issue. I'm happy with the coverage provided by the number of browsers supported.
