### ISSUE TITLE
Change -0px to 0

### ISSUE THREAD

**Issue by tschoffelen** [draeton/stitches#18]
The sprite editor sometimes outputs things like "background-position: -0px -0px". This could be changed to '0px' or just '0' for better, more readable CSS.

**Comment by draeton** [comment]
This is a fair point. I really allowed this assignment out of laziness; it's easier if all values are just formatted the same way, and "-0px" works just as well as "0". I should hope that any programmer worth his/her salt understands that -0 === 0, but there is the additional concern of wasted bandwidth.

**Comment by draeton** [comment]
Completed in commit 59c497d
