### ISSUE TITLE
SCSS support added

### ISSUE THREAD

**Issue by ptheofan** [draeton/stitches#21]
Hi, I just added SCSS support. Everything works fine except for the example. Unfortunately I cannot figure out where it fails. The problem is that the css classes are not injected to the browser. Where should I look for it? After that I can make a pull request to share :)

btw: Love this tool :dancer:

**Comment by antipalindrome** [comment]
@ptheofan Did you ever finish this? I'd love to see the code as this is what I need at the moment.

**Comment by ptheofan** [comment]
It's been a long time since! With the rise of grunt I just stopped using it all together. Not sure if this helps you (or if you still need the changes), but I've pushed the modifications for scss/sass to my fork
https://github.com/ptheofan/stitches
