### ISSUE TITLE
Node cannot be inserted

### ISSUE THREAD

**Issue by titmael** [draeton/stitches#4]
Hi,

first thanks a lot for your plugin, so nice to use !

But i tried to use it on my own computer and didn't work.

So i downloaded th stitches-0.1.4 zip, unziped it, created an html page as you say.

JS and CSS are in the good folder, but when i try the page i get those 2 errors (in french) :

Erreur : mal formé
Fichier Source : file:///C:/Documents%20and%20Settings/Administrator/Desktop/stitches-0.1.4/js/stitches.html
Ligne : 10, Colonne : 75
Code Source :
            < a href="javascript:void(0)" class="disabled dlsprite" target=_blank>Sprite &raquo;</ a>

---

Erreur : uncaught exception: [Exception... "Node cannot be inserted at the specified point in the hierarchy"  code: "3" nsresult: "0x80530003 (NS_ERROR_DOM_HIERARCHY_REQUEST_ERR)"  location: "file:///C:/Documents%20and%20Settings/Administrator/Desktop/stitches-0.1.4/js/jquery-1.7.1.min.js Line: 4"]

I use FF 4.0.1 (it is my working computer, cannot update FF for now)

**Comment by draeton** [comment]
Thanks for submitting this issue. I need to add a note to the documentation--because this project using the HTML5 File API, you have to host the code on a server to use it. You may either host the code remotely, or start a local server instance, like Tomcat.

**Comment by titmael** [comment]
Hmm, is apache enough ?

**Comment by draeton** [comment]
You may use any server that allows you to access the page through an HTTP or HTTPS protocol.

**Comment by titmael** [comment]
Ok, i just tried and works fine with a server :)

**Comment by draeton** [comment]
Glad I could help :-)
